[workspace]
members = [
  "introspection-engine/core",
  "introspection-engine/connectors/introspection-connector",
  "introspection-engine/connectors/sql-introspection-connector",
  "introspection-engine/introspection-engine-tests",
  "migration-engine/cli",
  "migration-engine/connectors/migration-connector",
  "migration-engine/connectors/sql-migration-connector",
  "migration-engine/core",
  "migration-engine/migration-engine-tests",
  "query-engine/connectors/query-connector",
  "query-engine/connectors/sql-query-connector",
  "query-engine/core",
  "query-engine/query-engine",
  "prisma-fmt",
  "libs/datamodel/core",
  "libs/datamodel/connectors/datamodel-connector",
  "libs/datamodel/connectors/sql-datamodel-connector",
  "libs/json-rpc-stdio",
  "libs/prisma-inflector",
  "libs/sql-schema-describer",
  "libs/test-cli",
  "libs/user-facing-errors",
  "libs/prisma-models",
  "libs/prisma-value",
  "libs/feature-flags",
  "libs/native-types",
]

[patch.crates-io]
rust_decimal = {git = "https://github.com/pimeys/rust-decimal", branch = "pgbouncer-mode"}

[profile.dev.package.backtrace]
opt-level = 3
