[package]
authors = []
edition = "2018"
name = "sql-query-connector"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
itertools = "0.8"
rand = "0.7"
rust_decimal = {git = "https://github.com/pimeys/rust-decimal", branch = "pgbouncer-mode"}
serde_json = "1.0"
thiserror = "1.0"
tokio = "0.2.13"
uuid = "0.8"

[dependencies.quaint]
features = ["full", "tracing-log"]
git = "https://github.com/prisma/quaint"

[dependencies.connector-interface]
package = "query-connector"
path = "../query-connector"

[dependencies.prisma-models]
features = ["sql-ext"]
path = "../../../libs/prisma-models"

[dependencies.prisma-value]
features = ["sql-ext"]
path = "../../../libs/prisma-value"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.datamodel]
path = "../../../libs/datamodel/core"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.cuid]
git = "https://github.com/prisma/cuid-rust"

[dependencies.user-facing-errors]
features = ["sql"]
path = "../../../libs/user-facing-errors"
