[package]
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"
name = "sql-introspection-connector"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.17"
datamodel = {path = "../../../libs/datamodel/core"}
sql-datamodel-connector = {path = "../../../libs/datamodel/connectors/sql-datamodel-connector"}
datamodel-connector = {path = "../../../libs/datamodel/connectors/datamodel-connector"}
native-types = {path = "../../../libs/native-types"}
introspection-connector = {path = "../introspection-connector"}
once_cell = "1.3"
prisma-value = {path = "../../../libs/prisma-value"}
regex = "1.2"
rust_decimal = {git = "https://github.com/pimeys/rust-decimal", branch = "pgbouncer-mode"}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
sql-schema-describer = {path = "../../../libs/sql-schema-describer"}
thiserror = "1.0.9"
tokio = {version = "0.2.13", features = ["rt-threaded", "time"]}
tracing = "0.1.10"
tracing-futures = "0.2.0"
user-facing-errors = {path = "../../../libs/user-facing-errors", features = ["sql"]}

[dependencies.quaint]
features = ["single"]
git = "https://github.com/prisma/quaint"

[dev-dependencies]
barrel = {git = "https://github.com/prisma/barrel.git", features = ["sqlite3", "mysql", "pg", "mssql"], branch = "mssql-support"}
pretty_assertions = "0.6.1"
test-macros = {path = "../../../libs/test-macros"}
test-setup = {path = "../../../libs/test-setup"}
